### ISSUE TITLE
[Bug]: Picker in iOS Safari occasionally selects item 1-2 slots above clicked item

### ISSUE THREAD

**Issue by theanAdobe** [adobe/spectrum-web-components#4697]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

picker

### Expected behavior

When clicking/touching a menu item in the picker, it should always select the item that was clicked/touched.

### Actual behavior

When clicking/touching a menu item in the picker, it occasionally selects the item 1 to 2 items above the clicked item.

### Screenshots

https://github.com/user-attachments/assets/fcb8f50a-88cd-433e-ad98-f7b431678be9

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/H4Yrm8QvcXAdQTKd1yTy/src/index.ts?p=stories **in an iOS Safari environment**. This does not repro for me on MacOS Safari, nor on Chrome's mobile-emulation.
2. In the storybook frame, click on the "Selection type" Picker to open the Picker Menu. The Menu should be a "Tray" coming up from the bottom, since it is in a mobile environment.
3. Click one of the menu options. I've had better consistency choosing an item different from the currently selected item (i.e. going from Option 4 to Option 5 and back repeatedly)
4. See that the Picker is showing Option 2 or 3 instead of the item selected.

### Sample code or abstract reproduction which illustrates the problem

The below sandbox has a plain picker with many items, which I have reproed this bug on. The more items seems to make it easier for me to to trigger the issue. When the number of items is 5 or less, I have never been able to trigger the issue.

https://studio.webcomponents.dev/edit/H4Yrm8QvcXAdQTKd1yTy/src/index.ts?p=stories

### Severity

SEV 3

**Comment by theanAdobe** [comment]
I just recalled that I was not able to repro this with <sp-picker> for some prior version of SWC that Adobe Express was using. Might have been SWC 0.44 or earlier? Maybe that might help investigation.

**Comment by najikahalsema** [comment]
This was fixed in the latest version of SWC. Updating should resolve this issue. @theanAdobe

**Comment by theanAdobe** [comment]
@najikahalsema -- If I go to the main [SWC picker page](https://opensource.adobe.com/spectrum-web-components/components/picker/) today, and use the [provided "sandbox" link](https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/guTpKeAjgecibF150Qbg/src/index.ts?p=stories), I can still reproduce the error on my iPhone 14, and in the XCode iPhone 15-Simulators.

Video of actual iPhone 14 reproing the issue:
https://github.com/user-attachments/assets/70a57603-2daa-415b-a27b-261978e8aa4c

Is the opensource sandbox using an older SWC somehow? If so, that's probably fine, but please at least provide a sandbox to me where the new version of SWC is imported for me to verify.

**Comment by theanAdobe** [comment]
Updating again 2+ months afterwards, it no longer repros on my phone. I cannot tell whether the latest version was slow to update into the official SWC sandbox, or if the resolver here was too quick and didn't wait for the change to be actually visible in the sandboxes, or if some iOS change between 18.1 and 18.3 fixed things. Still, the bottom line is that it seems to be resolved now.
